# Week 4: Baseline Model
- Train a linear regression as the first model
- Evaluate using R^2 on test set
- Record baseline results

In [1]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
from pathlib import Path

data_clean = pd.read_csv("data_clean.csv")

In [2]:
# loading in test/train split data
filepath = r"C:\Users\julia\downloads\IDX_summer_internship"

train_df = pd.read_csv(filepath + r"\train_cleaned.csv", low_memory=False)
test_df = pd.read_csv(filepath + r"\test_cleaned.csv", low_memory=False)

print(f"Training rows: {len(train_df):,}")
print(f"Testing rows:  {len(test_df):,}")
print(f"Columns: {train_df.shape[1]}")

Training rows: 118,196
Testing rows:  12,024
Columns: 299

In [20]:
# chosing target variable, creating x and y

target = "ClosePrice"
x_train = train_df.drop(columns=["ClosePrice"]) # we want to train on ClosePrice so we remove it here
x_test = test_df.drop(columns=["ClosePrice"])

y_train = train_df['ClosePrice']
y_test = test_df['ClosePrice']

drop_cols = [                   # these are based on what Aidan said in the slack
    "CloseDate",                # stuff like days on market are only known after the close
    "ListPrice",                # everything else introduces leakages
    "OriginalListPrice",
    "ListingKey",
    "ListingKeyNumeric",
    "DaysOnMarket"
]

x_train = x_train.drop(columns=drop_cols, errors="ignore") # dropping the rest of the leakage or unnecessary columns
x_test = x_test.drop(columns=drop_cols, errors="ignore")

drop_cols.extend([             # string values that interrupt the linear regression that made it through preprocessing
    "City",
    "HighSchoolDistrict",
    "PostalCode"
])

x_train = x_train.drop(columns=drop_cols, errors="ignore")
x_test = x_test.drop(columns=drop_cols, errors="ignore")

In [25]:
# training the linear regression model

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train, y_train)

LinearRegression()

In [27]:
# predict on the test set
y_pred = lr.predict(x_test)

In [29]:
# evaluate on R^2

from sklearn.metrics import r2_score, mean_absolute_error

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"Baseline R^2: {r2:.4f}")
print(f"Baseline MAE: ${mae:,.2f}")

Baseline R^2: 0.0390
Baseline MAE: $696,625.65

In [33]:
# record baseline
baseline_results = pd.DataFrame({
    "Model": ["Linear Regression"],
    "R2": [r2],
    "MAE": [mae]
})

baseline_results

               Model        R2            MAE
0  Linear Regression  0.039002  696625.652372

In [44]:
coef_df = pd.DataFrame({
    "Feature": x_train.columns,
    "Coefficient": lr.coef_
})

coef_df = coef_df.reindex(
    coef_df["Coefficient"].abs().sort_values(ascending=False).index
)

coef_df.head(50)

                                               Feature   Coefficient
231  BuyerAgentAOR_TUOLUMNECOUNTYASSOCIATIONOFREALTORS -1.334854e+07
268                      ListAgentAOR_PACIFICSOUTHWEST  4.759134e+06
14                                         LotSizeArea  3.694654e+06
262                   ListAgentAOR_NORTHSANDIEGOCOUNTY  3.536636e+06
4                                           LivingArea  3.457045e+06
76                              CountyOrParish_TRINITY -2.790666e+06
212                     BuyerAgentAOR_PACIFICSOUTHWEST -2.641571e+06
223                 BuyerAgentAOR_SANLUISOBISPOCOASTAL  2.459454e+06
29                      CountyOrParish_FOREIGN COUNTRY -2.447643e+06
140  BuyerOfficeAOR_SOUTHWESTLOUISIANAASSOCIATIONOF... -2.363629e+06
252                                ListAgentAOR_LAGUNA  1.856859e+06
70                             CountyOrParish_SISKIYOU -1.803378e+06
53                          CountyOrParish_OTHER STATE -1.794546e+06
206                  BuyerAgentAOR_NORTHSANDIEGOCOUNTY -1.772923e+06
174                          Levels_TWO,MULTISPLIT,ONE -1.653933e+06
58                           CountyOrParish_SAN BENITO -1.560342e+06
45                                CountyOrParish_MODOC -1.514215e+06
21                               CountyOrParish_AMADOR -1.371519e+06
51                                CountyOrParish_OTHER -1.362170e+06
23                            CountyOrParish_CALAVERAS -1.289228e+06
171                             Levels_THREEORMORE,ONE -1.281775e+06
207                   BuyerAgentAOR_NORTHSANLUISOBISPO  1.273682e+06
261                               ListAgentAOR_NEWPORT  1.255429e+06
30                               CountyOrParish_FRESNO -1.223185e+06
75                               CountyOrParish_TEHAMA -1.178578e+06
218                           BuyerAgentAOR_PISMOCOAST  1.159331e+06
32                             CountyOrParish_HUMBOLDT -1.122793e+06
77                               CountyOrParish_TULARE -1.070557e+06
40                               CountyOrParish_MADERA -1.054910e+06
199                               BuyerAgentAOR_MALIBU  1.026719e+06
166                          Levels_ONE,TWO,MULTISPLIT -1.019019e+06
38                               CountyOrParish_LASSEN -1.012702e+06
28                            CountyOrParish_EL DORADO -9.979338e+05
133                BuyerOfficeAOR_SANLUISOBISPOCOASTAL -9.860337e+05
81                                 CountyOrParish_YUBA -9.811173e+05
177                  Levels_TWO,THREEORMORE,MULTISPLIT -9.809186e+05
128  BuyerOfficeAOR_SACRAMENTOASSOCIATIONOFREALTORSINC -9.590514e+05
31                                CountyOrParish_GLENN -9.018187e+05
36                                CountyOrParish_KINGS -8.722079e+05
131                        BuyerOfficeAOR_SANFRANCISCO -8.682371e+05
64                            CountyOrParish_SAN MATEO  8.492987e+05
158                                 StateOrProvince_OS  8.458801e+05
168              Levels_ONE,TWO,THREEORMORE,MULTISPLIT  8.355569e+05
197                           BuyerAgentAOR_LAKECOUNTY  8.340086e+05
74                               CountyOrParish_SUTTER -8.264770e+05
22                                CountyOrParish_BUTTE -8.169047e+05
33                             CountyOrParish_IMPERIAL -8.114886e+05
111                             BuyerOfficeAOR_NEWPORT  8.094777e+05
42                             CountyOrParish_MARIPOSA -8.037894e+05
25                               CountyOrParish_COLUSA -7.806002e+05